const waitForLoad=tabId=>new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{chrome.tabs.onUpdated.removeListener(listener);reject(new Error('O LinkedIn demorou para carregar.'))},45000);const listener=(id,info)=>{if(id!==tabId||info.status!=='complete')return;clearTimeout(timeout);chrome.tabs.onUpdated.removeListener(listener);setTimeout(resolve,1600)};chrome.tabs.onUpdated.addListener(listener)});
const pageUrl=(raw,page)=>{const url=new URL(raw);url.searchParams.delete('currentJobId');url.searchParams.set('start',String(page*25));return url.toString()};
const automaticTabs=new Set();let lastUserSearch=null;const isSearch=url=>{try{const parsed=new URL(url);return parsed.hostname==='www.linkedin.com'&&parsed.pathname.startsWith('/jobs/search')}catch{return false}};
chrome.tabs.onActivated.addListener(async info=>{try{if(automaticTabs.has(info.tabId))return;const tab=await chrome.tabs.get(info.tabId);if(isSearch(tab.url))lastUserSearch={id:tab.id,url:tab.url,title:tab.title}}catch{}});
chrome.tabs.onUpdated.addListener((tabId,change,tab)=>{if(!automaticTabs.has(tabId)&&tab.active&&isSearch(change.url||tab.url))lastUserSearch={id:tabId,url:change.url||tab.url,title:tab.title}});

async function runCollection(rawUrl,existingTabId=null){
  const tab=existingTabId?await chrome.tabs.get(existingTabId):await chrome.tabs.create({url:'about:blank',active:true});if(existingTabId){await chrome.tabs.update(tab.id,{active:true});await new Promise(resolve=>setTimeout(resolve,1000))}else{automaticTabs.add(tab.id);const initialLoad=waitForLoad(tab.id);await chrome.tabs.update(tab.id,{url:pageUrl(rawUrl,0),active:true});await initialLoad}const unique=new Map();let totalPages=1;
  for(let page=0;page<totalPages;page++){
    if(page>0&&existingTabId){const clicked=await chrome.scripting.executeScript({target:{tabId:tab.id},func:pageNumber=>{const number=String(pageNumber);const controls=[...document.querySelectorAll('button,a')];const exact=controls.find(el=>!el.disabled&&((el.textContent||'').trim()===number||['page '+number,'página '+number].includes((el.getAttribute('aria-label')||'').trim().toLowerCase())));const next=controls.find(el=>!el.disabled&&/^(next|próxim|avançar)/i.test((el.getAttribute('aria-label')||'').trim()));const target=exact||next;if(!target)return false;target.click();return true},args:[page+1]});if(!clicked[0]?.result)break;await new Promise(resolve=>setTimeout(resolve,2200))}
    if(page>0&&!existingTabId){const loading=waitForLoad(tab.id);await chrome.tabs.update(tab.id,{url:pageUrl(rawUrl,page)});await loading}
    await chrome.scripting.executeScript({target:{tabId:tab.id},func:(current,total)=>{window.__codexPageInfo={page:current,max:total}},args:[page+1,page===0?0:totalPages]});
    const result=await chrome.scripting.executeScript({target:{tabId:tab.id},files:['page-collector.js']});const payload=result[0]?.result||{jobs:[],totalResults:0};const jobs=payload.jobs||[];if(page===0)totalPages=payload.totalResults?Math.max(1,Math.ceil(payload.totalResults/25)):100;let added=0;
    for(const job of jobs){if(!unique.has(job.link)){unique.set(job.link,job);added++}}
    if(!jobs.length||!added)break;
  }
  const jobs=[...unique.values()];
  await chrome.scripting.executeScript({target:{tabId:tab.id},func:items=>{const panel=document.querySelector('#codex-linkedin-collector-status')||document.body.appendChild(document.createElement('div'));panel.id='codex-linkedin-collector-status';panel.style.cssText='position:fixed;right:20px;bottom:20px;z-index:2147483647;background:#08783e;color:#fff;padding:16px 18px;border-radius:12px;box-shadow:0 8px 30px #0005;font:600 14px system-ui;max-width:390px';const esc=v=>`"${String(v??'').replace(/"/g,'""')}"`,cols=['titulo','empresa','local','descricao','link','coletado_em','pagina'];const csv='\uFEFF'+[cols.join(';'),...items.map(j=>cols.map(c=>esc(j[c])).join(';'))].join('\r\n');const download=(content,type,name)=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),3000)};const stamp=new Date().toISOString().slice(0,10);download(csv,'text/csv;charset=utf-8',`vagas-linkedin-${stamp}.csv`);setTimeout(()=>download(JSON.stringify(items,null,2),'application/json',`vagas-linkedin-${stamp}.json`),400);panel.textContent=`Concluído: ${items.length} vagas únicas exportadas.`},args:[jobs]});
}

chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=='LIST_LINKEDIN_SEARCHES')return;(async()=>{const tabs=await chrome.tabs.query({url:'https://www.linkedin.com/jobs/search/*'});const searches=await Promise.all(tabs.map(async tab=>{let total='total não identificado';try{const result=await chrome.scripting.executeScript({target:{tabId:tab.id},func:()=>{const match=document.body.innerText.match(/([\d.,]+)\s+resultados?/i);return match?`${match[1]} resultados`:''}});total=result[0]?.result||total}catch{}return{id:tab.id,url:tab.url,title:tab.title||'Pesquisa do LinkedIn',total,lastAccessed:tab.lastAccessed||0}}));searches.sort((a,b)=>b.lastAccessed-a.lastAccessed);sendResponse({ok:true,searches})})().catch(()=>sendResponse({ok:false,searches:[]}));return true});

chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type!=='START_AUTOMATIC_COLLECTION')return;(async()=>{try{let raw=message.url?.trim(),tabId=Number(message.tabId)||null,title=message.source||'link informado';if(!raw){let selected=lastUserSearch;if(!selected){const tabs=(await chrome.tabs.query({url:'https://www.linkedin.com/jobs/search/*'})).filter(tab=>!automaticTabs.has(tab.id));tabs.sort((a,b)=>(b.lastAccessed||0)-(a.lastAccessed||0));selected=tabs[0]}raw=selected?.url;tabId=selected?.id;title=selected?.title||'busca aberta';if(!raw)throw new Error('Nenhuma busca do LinkedIn foi visitada.')}const url=new URL(raw);if(!isSearch(url.toString()))throw new Error('Busca inválida.');sendResponse({ok:true,source:title});runCollection(url.toString(),tabId).catch(console.error)}catch(error){sendResponse({ok:false,error:error.message||'Cole um link válido da busca de vagas do LinkedIn.'})}})();return true});
