import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';

const read=path=>readFile(new URL(path,import.meta.url),'utf8');

test('catálogo oferece stacks selecionáveis',async()=>{const source=await read('../extensao-linkedin/stacks.js'),context={};vm.createContext(context);vm.runInContext(source,context);assert.ok(context.STACK_CATALOG.length>=25);for(const id of ['java','javascript','python','aws','azure','docker','kubernetes','salesforce'])assert.ok(context.STACK_CATALOG.some(stack=>stack.id===id))});

test('filtro mantém somente vagas compatíveis e anota stacks',async()=>{const stackSource=await read('../extensao-linkedin/stacks.js'),background=await read('../extensao-linkedin/background.js'),noop={addListener(){},removeListener(){}},context={chrome:{tabs:{onActivated:noop,onUpdated:noop},runtime:{onMessage:noop}},importScripts(){}};vm.createContext(context);vm.runInContext(stackSource,context);vm.runInContext(background,context);const jobs=[{titulo:'Backend Java',descricao:'Spring Boot e AWS',link:'1'},{titulo:'Designer',descricao:'Figma',link:'2'}],filtered=context.applyStackFilter(jobs,{selectedStacks:['java'],customTerms:''});assert.equal(filtered.length,1);assert.deepEqual([...filtered[0].stack],['Java','Spring','AWS'])});
test('modo todas exige cada stack e termos excluídos removem a vaga',async()=>{const stackSource=await read('../extensao-linkedin/stacks.js'),background=await read('../extensao-linkedin/background.js'),noop={addListener(){},removeListener(){}},context={chrome:{tabs:{onActivated:noop,onUpdated:noop},runtime:{onMessage:noop}},importScripts(){}};vm.createContext(context);vm.runInContext(stackSource,context);vm.runInContext(background,context);const jobs=[{titulo:'Backend Java AWS',descricao:'Spring Boot',link:'1'},{titulo:'Backend Java',descricao:'Spring Boot',link:'2'},{titulo:'Java AWS estágio',descricao:'Spring Boot',link:'3'}],all=context.applyStackFilter(jobs,{selectedStacks:['java','aws'],stackMode:'all',customTerms:'',excludedTerms:'estágio'});assert.deepEqual(all.map(job=>job.link),['1']);const custom=context.applyStackFilter(jobs,{selectedStacks:[],stackMode:'all',customTerms:'Spring Boot',excludedTerms:''});assert.equal(custom.length,3)});

test('painel salva filtros, destinos e testa o Radar',async()=>{const [html,script]=await Promise.all([read('../extensao-linkedin/dashboard.html'),read('../extensao-linkedin/dashboard.js')]);assert.match(html,/id="stack-options"/);assert.match(html,/id="stack-mode"/);assert.match(html,/id="excluded-terms"/);assert.match(html,/id="download-folder"/);assert.match(html,/id="send-radar"/);assert.match(html,/id="test-radar"/);assert.match(script,/chrome\.storage\.local\.set/);assert.match(script,/selectedStacks/);assert.match(script,/stackMode/);assert.match(script,/excludedTerms/);assert.match(script,/portalToken/);assert.match(script,/action:'test'/);assert.match(script,/Conexão confirmada/)});

test('service worker filtra, baixa e envia ao Radar',async()=>{const source=await read('../extensao-linkedin/background.js');assert.match(source,/applyStackFilter/);assert.match(source,/chrome\.downloads\.download/);assert.match(source,/authorization.*Bearer/);assert.match(source,/sendToRadar/)});
test('service worker mostra aceitas e rejeitadas pelo perfil do Radar',async()=>{const source=await read('../extensao-linkedin/background.js');assert.match(source,/radar\.accepted/);assert.match(source,/radar\.rejected/);});

test('manifest limita integração externa ao Radar conhecido',async()=>{const manifest=JSON.parse(await read('../extensao-linkedin/manifest.json'));assert.equal(manifest.version,'2.2.0');assert.ok(manifest.permissions.includes('storage'));assert.ok(manifest.permissions.includes('downloads'));assert.deepEqual(manifest.host_permissions,['https://www.linkedin.com/*','https://radar-carreira-almir-v2.prof-andreiamr.chatgpt.site/*'])});
